### ISSUE TITLE
Scenario 3 example - bump is after build

### ISSUE THREAD

**Issue by DavidThielen** [vers-one/dotnet-project-version-updater#5]
Hi;

Shouldn't the version number bump be after `run: dotnet build`? Correct me if I'm wrong but the exampl3 you have will build the project, then bump the version. Or am I not understanding something?

thanks - dave

**Comment by vers-one** [comment]
Hi Dave,

It depends on your use case. If you want to check that the current commit can be built successfully and increase the build number only when the build succeeded, then you would have the build command first and the build number bump after that. On the other hand, if you want to publish the build artifacts with the new version, then you would have the version bump before the build command.

**Comment by DavidThielen** [comment]
@vers-one thanks for the reply. First off, the functionality in this is well thought out.

Now on to my question. Your reply made me think about this better. What I think I need is in my existing yml file, in its handling of a push to master, before it compiles, it bumps the version.

I think this needs to happen in my existing yml because otherwise:
1. main.yml process a push to master, which includes compiling the project.
2. bump.yml increases the version number.
3. main.yml sees the change to master and kicks off its process again.

Am I not understanding this right? Is there a way to just add "bump..." to my existing action script?

thanks - dave

**Comment by vers-one** [comment]
This step:
```
- name: Bump build version
  id: bump
  uses: vers-one/dotnet-project-version-updater@v1.3
  with:
    file: "src/MyProject.csproj"
    version: bump-build
```
will change the version in the local copy of the `src/MyProject.csproj` file, but it will not push the changes into the repository by itself. In order to push the changes, you will need to have an extra push step, e.g.:
```
- run: |
    git config user.name "Your Name"
    git config user.email "your-email@users.noreply.github.com"
    git add .
    git commit -m "Bump project version to ${{ steps.bump.outputs.newVersion }}"
    git push
```

If you configure this action to run on every push event to the same branch and you are concerned that this might create a cycle when the action pushes the changes and thus triggers the same workflow, you don't need to worry: GitHub prevents such cycles from happening by [not letting a workflow trigger another workflow](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow). If for some reason your action does need to trigger another workflow and you have some steps to enable that (e.g. by supplying your personal access token instead of `GITHUB_TOKEN`), you will need to add [one of the action skip markers](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/) into your commit message in the push step.
